### ISSUE TITLE
SEC_SELINUX enforcing

### ISSUE THREAD

**Issue by xpirt** [flar2/starlte#1]
Hi flar2, this is not an issue, but a feature request. 

Wanted just to let you know that Samsung forces selinux to enforcing through SEC_SELINUX (ref: https://github.com/mwilky/G95x_renovate/commit/072c2b274a53542b61d067abbd61830181cedebc), it would be nice if you could remove it and let the user decide wheter to use permissive or enforcing, maybe through an aroma option? Or you can keep it enforcing but let developers change it in ramdisk (which is not possible at the moment)

This will be quite useful for future custom roms which may come (tested myself with a deodexed system and modified system apps).

Thanks in advance!

**Comment by DeadlyMelqn** [comment]
Just removing Samsung's always enforce should be good enough. Then you can easily switch it with "set enforce", with mtweaks and so on.

**Comment by xpirt** [comment]
It's still possible to change it through setenforce. That was not what I was asking.

**Comment by flar2** [comment]
Okay, in the interests of allowing people to experiment.

**Comment by flar2** [comment]
That's pretty messy patch though, I can't merge that.  I'll have to look into it further.

**Comment by xpirt** [comment]
Now this is solved, thanks @flar2!

Closed.
